import type { Metadata, Viewport } from "next";
import { SplashScreen } from "@/components/splash-screen/SplashScreen";
import { Header } from "@/components/header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#ffffff",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full flex flex-col">
        <SplashScreen />
        <div data-page-content className="flex flex-1 flex-col h-full w-full relative overflow-hidden"><Header />{children}</div>
      </body>
    </html>
  );
}
